/**
 * Builds the web app (installable on the iPhone home screen, works offline):
 * 1. Expo web export into dist/
 * 2. Home-screen tags in index.html
 * 3. Service worker that caches every file (offline use, update on next launch)
 * 4. 404.html so that GitHub Pages serves the app on any route
 */
import { execSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';

const BASE = '/App-CE2';
const DIST = 'dist';

execSync(`npx expo export --platform web --output-dir ${DIST} --clear`, { stdio: 'inherit' });

// Icon version in the URL so that the iPhone does not keep an old icon in its cache.
const iconVersion = createHash('sha256').update(readFileSync('public/icons/icon-180.png')).digest('hex').slice(0, 8);
const head = `
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-title" content="Repères CE2" />
    <meta name="apple-mobile-web-app-status-bar-style" content="default" />
    <meta name="theme-color" content="#1F4E9C" />
    <link rel="apple-touch-icon" href="${BASE}/icons/icon-180.png?v=${iconVersion}" />
    <link rel="manifest" href="${BASE}/manifest.webmanifest" />`;
const register = `
    <script>
      if ('serviceWorker' in navigator) {
        window.addEventListener('load', function () {
          navigator.serviceWorker.register('${BASE}/sw.js', { scope: '${BASE}/' });
        });
      }
    </script>`;

const indexPath = join(DIST, 'index.html');
let html = readFileSync(indexPath, 'utf8');
html = html.replace('<html lang="en">', '<html lang="fr">').replace('</head>', `${head}\n  </head>`).replace('</body>', `${register}\n  </body>`);
// Avoid the page bouncing and zooming like a website on the iPhone.
html = html.replace(/<meta name="viewport"[^>]*>/, '<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />');
writeFileSync(indexPath, html);
writeFileSync(join(DIST, '404.html'), html);

function listFiles(dir) {
  return readdirSync(dir).flatMap((name) => {
    const path = join(dir, name);
    return statSync(path).isDirectory() ? listFiles(path) : [path];
  });
}

const files = listFiles(DIST)
  .map((path) => relative(DIST, path).split('\\').join('/'))
  .filter((path) => path !== 'sw.js' && path !== '404.html' && path !== 'metadata.json')
  // Voice clips (about 20 MB) are cached when first played, not downloaded upfront.
  .filter((path) => !path.startsWith('voice/'));
const hash = createHash('sha256');
for (const file of files) hash.update(file).update(readFileSync(join(DIST, file)));
const version = hash.digest('hex').slice(0, 12);
const urls = [`${BASE}/`, ...files.map((f) => `${BASE}/${f}`)];

writeFileSync(
  join(DIST, 'sw.js'),
  `// Generated by scripts/build-web.mjs – version ${version}
const CACHE = 'reperes-ce2-${version}';
const VOICE = 'reperes-ce2-voice-v2';
const FILES = ${JSON.stringify(urls)};
self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(FILES)));
  self.skipWaiting();
});
self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) => Promise.all(keys.filter((key) => key !== CACHE && key !== VOICE).map((key) => caches.delete(key)))),
  );
  self.clients.claim();
});
self.addEventListener('fetch', (event) => {
  if (event.request.method !== 'GET') return;
  if (event.request.url.includes('/voice/')) {
    event.respondWith(
      caches.open(VOICE).then((cache) =>
        cache.match(event.request).then(
          (cached) => cached || fetch(event.request).then((response) => {
            if (response.ok) cache.put(event.request, response.clone());
            return response;
          }),
        ),
      ),
    );
    return;
  }
  event.respondWith(
    caches.match(event.request, { ignoreSearch: true }).then(
      (cached) => cached || fetch(event.request).catch(() => caches.match('${BASE}/index.html')),
    ),
  );
});
`,
);
console.log(`✓ Web app ready in ${DIST}/ (${files.length} files, version ${version})`);
